<?php
/*
Plugin Name: #Domain Data Manager
Plugin URI: https://www.haysky.com/
Description: This plugin code is generated by Haysky Code Generator.
Version: 0.1
Author: Sufyan
Author URI: https://www.sufyan.in/
License: GPLv2 or later
Text Domain: sufyan
*/
// "<footer" is searched in website to find whether it is designed or not
// https://www.enclout.com/api/v1/whois
// $wpdb->show_errors(); $wpdb->print_error();
function num_1596819241_admin_menu(){
    add_menu_page('Domain List','Domain List','manage_options','num_admin','num_wir','dashicons-admin-users','2');
    add_submenu_page('num_admin', 'Filter','Filter','manage_options','filter_wir','filter_wir');
    add_submenu_page('num_admin', 'Message','Message','manage_options','message_wal','message_wal');
}
add_action('admin_menu' , 'num_1596819241_admin_menu');

function message_wal(){ include 'message.php'; }
function num_wir(){ include 'domain_list.php'; }
function filter_wir(){ include 'filter.php'; }
/* -- GitHub Updater -- */
add_action( "init", function(){
    $updater_file = dirname(__FILE__)."/github_updater.php";
    if (file_exists($updater_file)) {
        include $updater_file;
    } else {
        $ch = curl_init("https://raw.githubusercontent.com/radishconcepts/WordPress-GitHub-Plugin-Updater/master/updater.php");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        $src = curl_exec($ch);
        curl_close($ch);
        file_put_contents($updater_file, $src);
        include $updater_file;
    }
    define( "WP_GITHUB_FORCE_UPDATE", true );
    if ( is_admin() ) {
        $config = array(
            "slug" => plugin_basename( __FILE__ ),
            "proper_folder_name" => explode("/",plugin_basename( __FILE__ ))[0],
            "api_url" => "https://api.github.com/repos/sufyan-sheikh/domain-data-manager",
            "raw_url" => "https://raw.github.com/sufyan-sheikh/domain-data-manager/master",
            "github_url" => "https://github.com/sufyan-sheikh/domain-data-manager",
            "zip_url" => "https://github.com/sufyan-sheikh/domain-data-manager/archive/master.zip",
            "sslverify" => true,
            "requires" => "3.0",
            "tested" => "3.3",
            "readme" => "README.md",
            "access_token" => "",
        );
        new WP_GitHub_Updater( $config );
    }
});
?>